name: "execution-performance"
on:
  workflow_dispatch:
  pull_request:
  schedule: 
    # Run every four hours
    - cron: "0 */4 * * *"

jobs:
  execution-performance:
    uses: aptos-labs/aptos-core/.github/workflows/workflow-run-execution-performance.yaml@main
    secrets: inherit
    with:
      GIT_SHA: ${{ github.event.pull_request.head.sha || github.sha }}
      RUNNER_NAME: executor-benchmark-runner

  spot-runner-execution-performance:
    uses: aptos-labs/aptos-core/.github/workflows/workflow-run-execution-performance.yaml@main
    secrets: inherit
    with:
      GIT_SHA: ${{ github.event.pull_request.head.sha || github.sha }}
      RUNNER_NAME: spot-runner